services:
  elasticsearch_exporter:
    restart: ${RESTART_POLICY}
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
     - '--es.uri=http://es01:9200'
    ports:
    - 9114:9114
    depends_on:
    - es01
