name: Container Image Build CI

on:
  push:
    branches:
      - main
      - deploy-*
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name:
        - search_service_image
        - search_front_image

    steps:
    - name: variables for service
      if: matrix.env == 'search_service_image'
      run: |
        echo "DOCKER_CONTEXT=." >> $GITHUB_ENV

    - name: variables for front
      if: matrix.env == 'search_front_image'
      run: |
        echo "DOCKER_CONTEXT=frontend" >> $GITHUB_ENV

    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: v0.6.0
        buildkitd-flags: --debug

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}/${{ matrix.image_name }}
        tags: |
          type=semver,pattern={{version}}
          type=ref,event=pr
          type=ref,event=branch
          type=sha,format=long

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.DOCKER_CONTEXT }}
        # Use runtime target, so that dev dependencies are not included
        target: runtime
        push: true
        file: Dockerfile
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.image_name }}:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.image_name }}:buildcache,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
